name: Hexo Deploy
on:
  push:
   branches:
     - master
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout source
       uses: actions/checkout@v4
       with:
         ref: master
     - name: Use Node.js 20.x
       uses: actions/setup-node@v4
       with:
         node-version: '20.x'
     - name: Setup hexo
       env:
         ACTION_DEPLOY_KEY: ${{ secrets.private_key }}
       # removed:"hexo-renderer-marked": "^6.0.0",
       run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "ying.zf@foxmail.com"
        git config --global user.name "pluto0x0"
        npm install hexo-cli -g
        npm install
     - name: Node and Hexo version
       run: |
        node -v
        hexo -v
     - name: Replace image path
       run: |
        echo $SHELL
        pwd
        exp='s/!\[\(.*\)\](\.\.\(\/img.\+\)) *\(= *[0-9]*x[0-9]*\)/![\1](\2 \3\)/g'
        for file in source/_posts/*.md; do
            echo in "$file":
            sed -n "${exp}p" "$file"
            sed -i "$exp" "$file"
        done
     - name: Hexo deploy
       run: |
        hexo clean
        hexo generate
        hexo deploy
